image:
  name : registry.gitlab.com/sahajsoft/gurukul2022/csv-validator
  entrypoint: [ "" ]

stages:
  - build
  - test

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: gradle-cache
  paths:
    - .gradle/
    - build/

front-end-unit-test:
  cache:
    key: npm
    policy: pull-push
    paths:
    - .npm
  stage: test
  script:
    - npm ci --cache .npm --prefer-offline
    - npm test

test-backend-and-build:
  stage: build
  script:
    - gradle build
    - echo "Jar Created in build/libs/"
  artifacts:
    paths:
      - build/libs/csv-validator-1.0.jar
    expire_in: 1 day
    

integration-test:
  stage: test
  cache: []
  needs:
    - job: test-backend-and-build
  script:
    - java -jar build/libs/csv-validator-1.0.jar &
    - npm ci
    - npm run e2e