image: gradle:latest

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Build Started"
    - gradle classes
    - echo "Build Completed"

unit-test:
  stage: test
  script:
    - echo "Test Started"
    - gradle test
    - echo "Test Passed"

front-end-unit-test:
  image: node:latest
  stage: test
  script:
    - echo "Front end unit test Started"
    - npm install
    - npm test
    - echo "Front end unit test Passed"

integration-test:
  image: node:latest
  stage: test
  script:
    - echo "Integeration test Started"
    - ./gradlew run
    - echo "Server is running"
    - npm run e2e
    - echo "Integeration test Passed"
