image:
  name : registry.gitlab.com/sahajsoft/gurukul2022/csv-validator
  entrypoint: [ "" ]

stages:
  - unit-test-and-build
  - integration-test

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: gradle-cache
  paths:
    - .gradle/
    - build/

front-end-unit-test:
  cache:
    key: npm
    policy: pull-push
    paths:
    - .npm
  stage: unit-test-and-build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm test

test-backend-and-build:
  stage: unit-test-and-build
  script:
    - gradle build
  artifacts:
    paths:
      - build/distributions
    expire_in: 1 day
    

integration-test:
  stage: integration-test
  cache: []
  needs:
    - job: test-backend-and-build
  script:
    - unzip -q build/distributions/CsvValidator-1.0-SNAPSHOT.zip -d build/distributions
    - sh build/distributions/CsvValidator-1.0-SNAPSHOT/bin/CsvValidator &
    - npm ci
    - npm run e2e