image: gradle:latest

stages:
  - build
  - test
  - frontend-test

# build-job:
#   stage: build
#   script:
#     - echo "Creating Classes"
#     - gradle classes
#     - echo "Classes Created"

# unit-test:
#   stage: test
#   script:
#     - echo "Initiating Tests"
#     - gradle test
#     - echo "All Tests Passed"

frontend-test:
  stage: frontend-test
  script:
    - echo "Initiating frontend test"
    - npm install
    - echo "Done"
