image:
  name : registry.gitlab.com/sahajsoft/gurukul2022/csv-validator
  entrypoint: [ "" ]

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Creating Jar"
    - ./gradlew --no-daemon jar
    - echo "Jar Created in build/libs/"
  artifacts:
    paths:
      - build/libs/csv-validator-1.0.jar
    expire_in: 1 day
    
back-end-unit-test:
  stage: test
  script:
    - gradle --no-daemon test

front-end-unit-test:
  stage: test
  script:
    - npm ci
    - npm test

integration-test:
  stage: test
  needs:
    - job: back-end-unit-test
    - job: front-end-unit-test
    - job: build-job
  script:
    - java -jar build/libs/csv-validator-1.0.jar &
    - npm ci
    - npm run e2e