image:
  name : registry.gitlab.com/sahajsoft/gurukul2022/csv-validator
  entrypoint: [ "" ]

stages:
  - build
  - test

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: gradle-cache
  paths:
    - .gradle/
    - build/

build-job:
  stage: build
  script:
    - echo "Creating Jar"
    - gradle jar
    - echo "Jar Created in build/libs/"
  artifacts:
    paths:
      - build/libs/csv-validator-1.0.jar
    expire_in: 1 day
    
back-end-unit-test:
  stage: test
  script:
    - gradle test

front-end-unit-test:
  cache:
    key: npm
    policy: pull-push
    paths:
    - .npm
  stage: test
  script:
    - npm ci --cache .npm --prefer-offline
    - npm test

integration-test:
  stage: test
  cache: []
  needs:
    - job: build-job
  script:
    - java -jar build/libs/csv-validator-1.0.jar &
    - npm ci
    - npm run e2e