image : gradle:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - gradle classes

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - gradle test
