image:
  name : registry.gitlab.com/sahajsoft/gurukul2022/csv-validator
  entrypoint: [ "" ]

stages:
  - dependencies
  - test

cache:
  key: node-and-gradle-deps
  paths:
    - node_modules/
    - build/
    - .gradle/

install-dependencies-and-compile-classes:
  stage: dependencies
  script:
    - npm install
    - gradle classes

back-end-unit-test:
  stage: test
  script:
    - gradle test

front-end-unit-test:
  stage: test
  script:
    - npm ci
    - npm test

integration-test:
  stage: test
  needs:
    - job: back-end-unit-test
    - job: front-end-unit-test
  script:
    - gradle run &
    - npm ci
    - npm run e2e