image:
  name: registry.gitlab.com/sahajsoft/gurukul2022/csv-validator
  entrypoint: [ "" ]

stages:
  - unit-test-and-build
  - integration-test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

variables:
  POSTGRES_DB: csv_validator
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test-db-user
  POSTGRES_HOST_AUTH_METHOD: trust

services:
  - name: postgres:14.2
    command: [ "psql","$POSTGRES_USER","-d","$POSTGRES_DB","-c", "CREATE TABLE csv_configuration
(
    config_id   SERIAL PRIMARY KEY,
    config_name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE fields
(
    field_id        SERIAL PRIMARY KEY,
    config_id       INT,
    field_name      VARCHAR NOT NULL,
    field_type      VARCHAR NOT NULL,
    is_null_allowed VARCHAR(2),
    pattern         VARCHAR,
    fixed_length    INT,
    min_length      INT,
    max_length      INT,
    CONSTRAINT fk_config
        FOREIGN KEY (config_id)
            REFERENCES csv_configuration (config_id)
            ON DELETE CASCADE
);

CREATE TABLE values
(
    value_id   SERIAL PRIMARY KEY,
    field_id   INT,
    value_name VARCHAR NOT NULL,
    CONSTRAINT fk_field_id
        FOREIGN KEY (field_id)
            REFERENCES fields (field_id)
            ON DELETE CASCADE
);

CREATE TABLE dependencies
(
    dependency_id            SERIAL PRIMARY KEY,
    field_id                 INT,
    dependent_on             VARCHAR NOT NULL,
    expected_dependent_value VARCHAR,
    expected_current_value   VARCHAR,
    CONSTRAINT fk_field_id
        FOREIGN KEY (field_id)
            REFERENCES fields (field_id)
            ON DELETE CASCADE
);" ]

cache:
  key: gradle-cache
  paths:
    - .gradle/
    - build/

#front-end-unit-test:
#  cache:
#    key: npm
#    policy: pull-push
#    paths:
#      - .npm
#  stage: unit-test-and-build
#  script:
#    - npm ci --cache .npm --prefer-offline
#    - npm test
#  timeout: 10m
#
#test-backend-and-build:
#  stage: unit-test-and-build
#  script:
#    - gradle build
#  artifacts:
#    paths:
#      - build/distributions
#    expire_in: 1 day
#  timeout: 10m


integration-test:
  stage: integration-test
  cache: [ ]
  #  needs:
  #    - job: test-backend-and-build
  script:
    - gradle build
    - source scripts/set-test-env.sh
    - unzip -q build/distributions/CsvValidator-1.0-SNAPSHOT.zip -d build/distributions
    - sh build/distributions/CsvValidator-1.0-SNAPSHOT/bin/CsvValidator &
    - npm ci
    - npm run e2e
  timeout: 15m
