image: gradle:latest

stages:
  - test

unit-test:
  stage: test
  script:
    - echo "Test Started"
    - gradle test
    - echo "Test Passed"

front-end-unit-test:
  image: node:latest
  stage: test
  script:
    - echo "Front end unit test Started"
    - npm install
    - npm test
    - echo "Front end unit test Passed"

integration-test:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - echo "Integeration test Started"
    - apt-get install -y default-jdk
    - ./gradlew run &
    - echo "Server is running"
    - npm install
    - npm run e2e
    - echo "Integeration test Passed"
