image: gradle:latest

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Build Started"
    - gradle classes
    - echo "Build Completed"

unit-test:
  stage: test
  script:
    - echo "Test Started"
    - gradle test
    - echo "Test Passed"
